//
//  DesignSystem.swift
//  Lumberjacked
//

import SwiftUI

// MARK: - Tokens

enum DesignSystem {
    enum CornerRadius {
        static let small: CGFloat = 8
        static let medium: CGFloat = 12
        static let large: CGFloat = 20
    }

    enum Font {
        static let screenTitle: SwiftUI.Font = .title.weight(.semibold)
        static let cardTitle: SwiftUI.Font = .title2.bold()
        static let sectionHeader: SwiftUI.Font = .headline
        static let body: SwiftUI.Font = .subheadline
        static let label: SwiftUI.Font = .caption
        static let badge: SwiftUI.Font = .caption2
    }
}

// MARK: - Color tokens
// Colors (brandBackground, brandSecondary, brandSecondaryLight,
// brandPrimaryText, brandPlaceholderText) are defined as colorsets
// in Assets.xcassets and auto-generated by Xcode.

// MARK: - BrandCard

private struct BrandCard: ViewModifier {
    var cornerRadius: CGFloat = DesignSystem.CornerRadius.medium

    func body(content: Content) -> some View {
        content
            .background(Color.brandSecondary)
            .clipShape(RoundedRectangle(cornerRadius: cornerRadius))
    }
}

extension View {
    func brandCard(cornerRadius: CGFloat = DesignSystem.CornerRadius.medium) -> some View {
        modifier(BrandCard(cornerRadius: cornerRadius))
    }
}

// MARK: - SectionLabel

private struct SectionLabelModifier: ViewModifier {
    func body(content: Content) -> some View {
        content
            .font(DesignSystem.Font.label)
            .textCase(.uppercase)
            .foregroundStyle(.secondary)
    }
}

extension View {
    func sectionLabel() -> some View {
        modifier(SectionLabelModifier())
    }
}
